### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Cybermaxs** [whyleee/nogit#7] opened 2015-07-11 08:06 UTC
I open another one because issue persists  using node > 0.11.5
It's impossible to list remotes, thus to use bower.
I have the same kind of error using git or http protocol.

HTTP 
-----
C:\issue>node node_modules\nogit\bin\git.js ls-remote --tags http://github.com/m
oment/moment.git
C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git-net\smart-htt
p.js:191
          if (line.trim() !== '# service=git-upload-pack') {
                  ^
TypeError: Cannot read property 'trim' of undefined
    at C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git-net\sm
art-http.js:191:19
    at read (C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git-
net\node_modules\push-to-pull\transform.js:14:32)
    at onRead (C:\issue\node_modules\nogit\node_modules\git-node\node_modules\gi
t-net\node_modules\push-to-pull\transform.js:31:14)
    at check (C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git
-node-platform\stream.js:45:16)
    at IncomingMessage.<anonymous> (C:\issue\node_modules\nogit\node_modules\git
-node\node_modules\git-node-platform\stream.js:28:5)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

GIT
-----

C:\issue>node node_modules\nogit\bin\git.js ls-remote --tags http://github.com/m
oment/moment.git
C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git-net\smart-htt
p.js:191
          if (line.trim() !== '# service=git-upload-pack') {
                  ^
TypeError: Cannot read property 'trim' of undefined
    at C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git-net\sm
art-http.js:191:19
    at read (C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git-
net\node_modules\push-to-pull\transform.js:14:32)
    at onRead (C:\issue\node_modules\nogit\node_modules\git-node\node_modules\gi
t-net\node_modules\push-to-pull\transform.js:31:14)
    at check (C:\issue\node_modules\nogit\node_modules\git-node\node_modules\git
-node-platform\stream.js:45:16)
    at IncomingMessage.<anonymous> (C:\issue\node_modules\nogit\node_modules\git
-node\node_modules\git-node-platform\stream.js:28:5)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by deenairn** [comment] 2015-08-05 12:59
This is happening for one of our projects as well. I have removed the references within it. This command does work with the installed version of Git.

```
C:\Project>.bin\git.cmd ls-remote --tags git://url

C:\Project\packages\NoGit.0.0.9\node_modules\nogit
\node_modules\git-node\node_modules\git-net\discover.js:18
    line = line.trim();
                ^
TypeError: Cannot call method 'trim' of undefined
    at onLine (C:\Project\packages\NoGit.0.0.9\nod
e_modules\nogit\node_modules\git-node\node_modules\git-net\discover.js:18:17)
    at read (C:\Project\packages\NoGit.0.0.9\node_
modules\nogit\node_modules\git-node\node_modules\push-to-pull\transform.js:14:32
)
    at onRead (C:\Project\packages\NoGit.0.0.9\nod
e_modules\nogit\node_modules\git-node\node_modules\push-to-pull\transform.js:31:
14)
    at check (C:\Project\packages\NoGit.0.0.9\node
_modules\nogit\node_modules\git-node\node_modules\git-node-platform\stream.js:45
:16)
    at Socket.<anonymous> (C:\Project\packages\NoG
it.0.0.9\node_modules\nogit\node_modules\git-node\node_modules\git-node-platform
\stream.js:28:5)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)```

**Comment by whyleee** [comment] 2015-08-06 07:16
Hi guys, the problem is in old `js-git` dependency. New version looks like a complete rewrite and it's not well documented, so I need some time for update. A couple of days ago I reimplemented and fixed `ls-remote` command, you can take the code in `vnext` branch. But I still need to update `clone` and test everything before I can update nogit version.

**Comment by Cybermaxs** [comment] 2015-08-07 06:47
ok thanks for your feedback. I will check when I have some free time

**Comment by whyleee** [comment] 2015-08-09 19:28
I updated `clone` command, but it only works with TCP transport now (`git://` urls). The code is still in `vnext` branch. I'm stuck with HTTP transport problem: my callback passed to "fetch" is never called and I can't figure out why :confused:. I created [an issue](https://github.com/creationix/js-git/issues/120) to js-git, maybe its owner can help. Otherwise I need to dig more into this problem..

**Comment by whyleee** [comment] 2015-11-01 18:02
`nogit` is updated to `0.1.0` with Node.js 0.12/4/5 support. The issue is fixed in this version.

**Closed** 2015-11-01 18:43 UTC
